name: E2E Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3.1.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Test with unittest
      run: |
        
        python tests/e2e/test_comparatori.py
        python tests/e2e/test_datapath.py
        python tests/e2e/test_fsm.py
