name: Linter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4.6.0
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy

    - name: Lint with flake8
      run: |
        
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # ignore not used import inside __init__.py and import position in unit_tests.py
        flake8 . --count \
                 --exit-zero \
                 --max-complexity=11 \
                 --exclude="*/build/*" --per-file-ignores="**/__init__.py:F401 **/__main__.py:F401 /tests/**.py:F401 blifparser/keywords/fsm.py:E742" \
                 --max-line-length=127 \
                 --statistics

    - name: Type check with mypy
      run: |
        mypy blifparser --strict
